apollographql/graphql-tag

printer.d.ts
Fixes #4 
> TypeScript error: /Users/scott/Documents/showcase/client/node_modules/apollo-client/index.d.ts(3,23): Error TS2307: Cannot find module 'graphql-tag/printer'.
It's not a solution, sort of workaround.
=> Fix missing 'graphql-tag/printer' module

.editorconfig, index.js
https://github.com/apollostack/graphql-tag/pull/9 introduced tabs. I have noticed only post merge. This PR fixes the style issue introduced by the #9 and adds .editorconfig to prevent future mistakes such as this one.
=> Enforce consistent indentation style

README.md, loader.js, test.js
I was wondering to create another module, but this is a file with 2 lines of code. 😄 
There are many benefits using `graphql-tag` as `webpack` loader:
-  Saves GraphQL ASTs processing on client-side
-  Optimizes bundle size
-  Enable queries to be separated from script over `.gql` files.
=> create webpack loader

README.md, loader.js, test.js
As per [webpack docs](https://webpack.github.io/docs/how-to-write-a-loader.html#flag-itself-cacheable-if-possible), loaders are better cached, it avoid `.graphql` files to be compiled when changes are not made.
=> cache webpack loader

fragment_definition.graphql, loader.js, test.js
The goal is to be able to do this with the webpack loader:
```
#import "fragment.graphql"
query {
author {
...authorDetails
}
}
```
with the following in `fragment.graphql`:
```
fragment authorDetails on Author {
firstName
lastName
}
```
This should be equivalent to:
```
query {
author {
...authorDetails
}
}
fragment authorDetails on Author {
firstName
lastName
}
```
in a single file.
=> Added ability to "#import" graphql files

README.md, loader.js
After the awesome #33 PR, loader writes es6 code `const` on final bundle.
=> fix loader to output only es5 script

index.js, package.json, test.js
Per #27, de-duplicating fragments as we're iterating over them to check for fragment name uniqueness.
This will result in the expression
```js
gql`query { ...SomeFragment } ${SomeFragment} ${SomeFragment}`
```
only emitting one of the fragment definitions
```js
gql`query { ...SomeFragment } fragment SomeFragment on SomeResource { someField }`
```
=> De-duplicating fragments in document

CHANGELOG.md, bundledPrinter.d.ts
There's no any right now and it breaks typescript compilation in some cases. 
@jnwng We need it in `apollo-angular`
=> Add typescript definitions for the bundledPrinter

CHANGELOG.md, bundledPrinter.d.ts, index.js, package.json
Most of the 1.3.0 changes were cherry-picked from master already, just merging some feature-branch changes back into master so we can release a 2.0 of `graphql-tag`.
This will be squashed so the commits don't look so crazy.
=> Merging 1.3.0 changes back into master

README.md
https://github.com/apollographql/graphql-tag/issues/49
=> feat(deps): Remove Printer and Parser re-exports

CHANGELOG.md, src/index.js, test.js
Current implementation throws an exception that the query isn't valid without providing information that the document was reduced to a single character by the implementation. Either the software should elegantly handle the case when parenthesis are added to the function  call or else return a useful error on usage.
=> Support use case of gql(``) vs gql``

loader.js, test.js
This fixes #27 for the case of webpack loader.
As imports are handled at runtime, the duplicity checks need to be performed at runtime, too. I added a "unique" function into every graphql module to makes sure no FragmentDefinition is used twice.
=> Ignore duplicate fragments from imports when using webpack loader

loader.js, src/index.js
this should fix https://github.com/apollographql/graphql-tag/issues/61
=> fix issue/61: split('/n') does not work on Windows

loader.js
At the moment Webpack loader parsing will fail if `.graphql` files have Unix line endings on Windows machine, because the parser will view the whole file as one line. This patch makes parser correctly understand lines no matter what kind of line endings is used, Unix, Mac or Windows.
=> Make parsing line endings kind agnostic

.flowconfig, package.json, src/index.js.flow
1. Declared `index.js.flow` in `src` directory.
2. On `bundle` it copies given flow definition to lib directory under the same name as `main` script in `package.json`.
3. Works out of the box with flow projects that uses `graphql-tag`.
Resolves #97
=> Add flow support

src/index.js, test.js
Connects to https://github.com/apollographql/graphql-tag/issues/81
This will add support for descriptors in schema files:
```graphql
type Foo {
bar: String
baz: Int
}
```
@stubailo, could you have a look at this? Or maybe @jnwng. Thanks!
=> feat(descriptors): add support for descriptors

README.md
Wanted to document a solution for React Native / Next.js users who want to use `graphql-tag`.
Addresses #31. @detrohutt PTAL!
=> Adding docs for `babel-plugin-import-graphql-ast`

loader.js, test.js
This allows them to be imported by name:
```
// query.gql
query MyQuery1 {
...
}
query MyQuery2 {
...
}
// some.js
import { MyQuery1, MyQuery2 } from 'query.gql'
// or
const Queries = require('query.gql');
...Queries.MyQuery1
...Queries.MyQuery2
```
In the case where there's only a single query, it remains backwards compatible. I'm not sure if this is desired or not... I considered putting it behind a loader option, but thought I'd ask here.
I believe this solves #119, but the wording in that issue is unclear to me so I'm not sure.
=> Webpack: support multiple query definitions per query file

index.d.ts, package.json, yarn.lock
Closes #138 
I used the broadest possible version range for `@types/graphql` that exports `DocumentNode` to get the biggest chance of deduping.
Also changed the string tag signature to not use `any`, like [`String.raw`](https://github.com/Microsoft/TypeScript/blob/0477f91dbad209809363323042f34926d3a6e175/lib/lib.es2015.core.d.ts#L544).
=> Typescript type safety

index.d.ts, package.json, yarn.lock
=> Reverting #141 until we can figure out why its throwing errors.

.tav.yml, .travis.yml, package.json, test/graphql-v0.11.js, test/graphql-v0.12.js, test/graphql.js, test/mocha.opts, yarn.lock
As new versions of `graphql` get released, its hard to figure out whether or not we're honoring our `peerDependencies` and actually supporting all versions of `graphql`. [test-all-versions](https://github.com/watson/test-all-versions) allows us to configure our compatibility matrix and run them on every PR to ensure that we know when we're making backwards-incompatible changes.
The test files here are split because while the functionality of `graphql-tag` does not differ between versions, the output of one of the packages we depend on _does_ differ. I'm capturing that difference by splitting the tests and confirming that, yes, we do support both versions. In the future, if a PR were to break one or both of the tests, we could then determine that we need to put through a major version …
=> Adding compatibility check for all supported versions of `graphql`

src/index.js, test/graphql.js
I'm experimenting with fragments on [react-apollo-fragments](http://github.com/lucasconstantino/react-apollo-fragments) and have reached a point to deal with fragment variables. The folks at the core of *graphql-js* project have added some experimental parsing for this, and I would love to use it in my own library. But as I use `graphql-tag`, as as this library does not export the full parser API below it, I'm decided to pull-request.
You can better understand what I'm looking for here https://github.com/graphql/graphql-js/blob/master/src/language/parser.js#L99-L115
I tried to find a workaround, but I found no way other than replace *graphql-tag* usage.
=> Added experimentalFragmentVariables compatibility.

loader.js
Fixes #158.
Use a regular for-loop instead of `Array.prototype.find` so the code generated by the loader doesn't break in IE11.
=> Fix IE11 support

README.md
I'm doing an official release of my package soon and in preparation for that, I changed the name because I didn't like it. I've updated the references and links in the README with the new name and URLs.
The old package and repo will remain available but users will get a deprecation warning when installing it asking them to switch to `babel-plugin-import-graphql`.
**Pull Request Labels**
=> Update deprecated package name

index.d.ts
=> Add DocumentNode to gql declaration

index.d.ts
This reverts commit ae792b67ef16ae23a0a7a8d78af8b698e8acd7d2. Based on #196 and #150, introducing the `DocumentNode` return value causes this library to break for existing TypeScript installations. I'm reverting this temporarily so we can release support for GraphQL v14 in a minor patch, and if we can't fix the TypeScript configuration, we'll release a major version with this commit back in.
/cc @felixfbecker @kamilkisiela since i still can't figure out how to fix the TypeScript installation in a non-breaking way.
=> Revert "Add DocumentNode to gql declaration (#196)"

.npmignore
Alternatively, you could use the `files` field in `package.json` to whitelist the stuff you do want to push to NPM.
=> Add `yarn.lock`, `.editorconfig`, and `.flowconfig` to `.npmignore`.

loader.js
**Pull Request Labels**
/label bug
I was using version 2.9.2 with the Webpack loader. On IE 11, I saw the following error:
Fragment was XXX used, but not defined
It turns out that on line 133 of loader.js, we have `var newRefs = new Set(opRefs);` and [IE 11 doesn't support "new Set(iterable)"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), so I rewrite it to add the members of opRefs to newRefs one by one using `forEach`, which resovles the issue.
=> Fix operations with fragments in the Webpack loader for IE 11

README.md
Initial loader support in CRA2 was reverted here: https://github.com/facebook/create-react-app/pull/5076
Using the macro https://github.com/evenchange4/graphql.macro the same can be achieved.
=> Updated CRA2 preprocess ability

CHANGELOG.md, index.d.ts
This PR modernizes/fixes the existing TypeScript declaration file as follows:
- The module declaration now better represents how exports are currently setup, by using module augmentation to give access to helper functions that are added to the `gql` function itself.
- Backwards compatibility has been maintained by re-exporting helper functions.
- Stronger typing changes; the first param of the `gql` template literal is now a read only string based array, and the `gql` return type is a `DocumentNode`. We're leveraging TS' [import types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types) functionality to reference the `DocumentNode` type, which will help avoid issues like the previously reverted attempts to do this in …
=> Update/fix the existing TS declaration file

index.d.ts
It seems that the typings from `v2.10.2` are not  exactly as expected.
Based on what i see in the [`gql`](https://github.com/apollographql/graphql-tag/blob/master/src/index.js#L158) function, it seems that the `literals` parameter accepts an array of strings **or** a string.
=> Fix gql typings

CHANGELOG.md, package.json
This will help tree-shaking when used with projects that have a dependency on `graphql-tag` (like `@apollo/client`).
Reference: https://github.com/apollographql/apollo-client/issues/6687
=> Clearly identify that `graphql-tag` doesn't have side effects

README.md
graphql-js returns 404 on npm: http://npmjs.com/package/graphql-js
=> Rename graphql-js to graphql

CHANGELOG.md, package.json, src/index.ts, src/tests.ts
Should fix #345. Tested by running `npm i typescript@3.7.x` and verifying that the package still compiles and passes tests.
=> Avoid TypeScript `import type ...` syntax for now.

src/index.ts
=> Avoid using Object.assign to attach extra properties to gql.

CHANGELOG.md, README.md, loader.js, src/tests.ts
This makes fragments a bit more convenient to use.
Any packages that use `graphql-tag/loader` under the hood will also benefit.
Likely fix for https://github.com/apollographql/graphql-tag/issues/102 and https://github.com/apollographql/graphql-tag/issues/251
Note that if the fragment references other fragments (using fragment spread), you will get a document that has multiple fragments in it.  In this case you will have to tell apollo which fragment you want using the `fragmentName` option.
=> Allow fragments to be imported by name when using the webpack loader

CHANGELOG.md, package.json
fixes https://github.com/apollographql/graphql-tag/issues/389
=> Include src for source maps

CHANGELOG.md
=> Mention PR #381 in CHANGELOG.md.

loader.js
Fixes this warning: `Syntax Error: NonErrorEmittedError: (Emitted value instead of an instance of Error) Query/mutation names are required for a document with multiple definitions`
=> Throw as Error to prevent certain issues

loader.js, src/tests.ts
Allow the webpack loader to distinct imports written with a space like:
```gql
```
I've stumbled on this while migrating a parcel project to webpack
In parcel imports work with a space, like in the example here: https://en.parceljs.org/graphQL.html#graphql
The change here allows for both `#import` and `# import` syntax to work
=> Loader: allow a space between `#` and `import` word in gql files
